# Generated by Django 4.1.3 on 2022-12-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0003_comment_post_delete_posteo_comment_post_padre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=250)),
                ('mensaje', models.TextField(max_length=3000)),
            ],
        ),
    ]
