# Generated by Django 4.1.2 on 2022-12-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
