# Generated by Django 4.1.2 on 2022-12-11 05:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0006_alter_comment_comentario_alter_post_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comentario',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
