# Generated by Django 4.1.2 on 2022-12-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0007_alter_comment_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='texto',
        ),
        migrations.AddField(
            model_name='post',
            name='cuerpo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comentario',
            field=models.TextField(default=''),
        ),
    ]
