# Generated by Django 4.1.3 on 2022-12-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0009_alter_post_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
