# Generated by Django 4.1.3 on 2022-12-13 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUsuarios', '0003_alter_userdata_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='aboutMe',
            new_name='about_me',
        ),
    ]
